USE [master]
GO
/****** Object:  Database [KralMessenger]    Script Date: 3/21/2023 2:39:37 PM ******/
CREATE DATABASE [KralMessenger]
GO
ALTER DATABASE [KralMessenger] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [KralMessenger].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [KralMessenger] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [KralMessenger] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [KralMessenger] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [KralMessenger] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [KralMessenger] SET ARITHABORT OFF 
GO
ALTER DATABASE [KralMessenger] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [KralMessenger] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [KralMessenger] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [KralMessenger] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [KralMessenger] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [KralMessenger] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [KralMessenger] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [KralMessenger] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [KralMessenger] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [KralMessenger] SET  ENABLE_BROKER 
GO
ALTER DATABASE [KralMessenger] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [KralMessenger] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [KralMessenger] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [KralMessenger] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [KralMessenger] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [KralMessenger] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [KralMessenger] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [KralMessenger] SET RECOVERY FULL 
GO
ALTER DATABASE [KralMessenger] SET  MULTI_USER 
GO
ALTER DATABASE [KralMessenger] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [KralMessenger] SET DB_CHAINING OFF 
GO
ALTER DATABASE [KralMessenger] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [KralMessenger] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [KralMessenger] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [KralMessenger] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'KralMessenger', N'ON'
GO
ALTER DATABASE [KralMessenger] SET QUERY_STORE = ON
GO
ALTER DATABASE [KralMessenger] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [KralMessenger]
GO
/****** Object:  Table [dbo].[MessageRecipients]    Script Date: 3/21/2023 2:39:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MessageRecipients](
	[MessageID] [int] NOT NULL,
	[RecipientID] [int] NOT NULL,
 CONSTRAINT [PK_MessageRecipients] PRIMARY KEY CLUSTERED 
(
	[MessageID] ASC,
	[RecipientID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Messages]    Script Date: 3/21/2023 2:39:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Messages](
	[MessageID] [int] IDENTITY(1,1) NOT NULL,
	[SenderID] [int] NOT NULL,
	[Subject] [varchar](50) NOT NULL,
	[Text] [varchar](max) NOT NULL,
	[SendDateTime] [datetime] NOT NULL,
	[IsDeleted] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MessageID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PasswordPolicies]    Script Date: 3/21/2023 2:39:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PasswordPolicies](
	[PasswordPolicyID] [int] IDENTITY(1,1) NOT NULL,
	[MinimumLength] [int] NOT NULL,
	[RequireUppercase] [bit] NOT NULL,
	[RequireLowercase] [bit] NOT NULL,
	[RequireNumbers] [bit] NOT NULL,
	[RequireSymbols] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PasswordPolicyID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 3/21/2023 2:39:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [varchar](50) NOT NULL UNIQUE,
	[Pasword] [varchar](100) NOT NULL,
	[PasswordPolicyID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Messages] ADD  DEFAULT ((0)) FOR [IsDeleted]
GO
ALTER TABLE [dbo].[MessageRecipients]  WITH CHECK ADD  CONSTRAINT [FK_Message] FOREIGN KEY([MessageID])
REFERENCES [dbo].[Messages] ([MessageID])
GO
ALTER TABLE [dbo].[MessageRecipients] CHECK CONSTRAINT [FK_Message]
GO
ALTER TABLE [dbo].[MessageRecipients]  WITH CHECK ADD  CONSTRAINT [FK_Recipient] FOREIGN KEY([RecipientID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[MessageRecipients] CHECK CONSTRAINT [FK_Recipient]
GO
ALTER TABLE [dbo].[Messages]  WITH CHECK ADD  CONSTRAINT [FK_SENDER] FOREIGN KEY([SenderID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[Messages] CHECK CONSTRAINT [FK_SENDER]
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD  CONSTRAINT [FK_PasswordPolicy] FOREIGN KEY([PasswordPolicyID])
REFERENCES [dbo].[PasswordPolicies] ([PasswordPolicyID])
GO
ALTER TABLE [dbo].[Users] CHECK CONSTRAINT [FK_PasswordPolicy]
GO
USE [master]
GO
ALTER DATABASE [KralMessenger] SET  READ_WRITE 
GO
